"""add customer to appointments

Revision ID: 5d063bd3dde3
Revises: fa5e2c0c928a
Create Date: 2026-08-12 02:33:02.897139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d063bd3dde3'
down_revision: Union[str, Sequence[str], None] = 'fa5e2c0c928a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['customer_id'], ['id'])
    op.drop_column('appointments', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'customer_id')
    # ### end Alembic commands ###
